### ISSUE TITLE
Save to ISO feature

### ISSUE THREAD

**Issue by btclinux** [DesobedienteTecnologico/dtails#17]
This will be useful option in GUI which can write modified system not only on USB stick but to ISO file too

**Comment by DesobedienteTecnologico** [comment]
Hi @btclinux , if you have a look at https://github.com/DesobedienteTecnologico/dtails#3--iso-vs-img
You can see that if your input is a .iso file from Tails it will return an .iso too.

1.1
![image](https://github.com/DesobedienteTecnologico/dtails/assets/52879067/41f1d488-5251-4160-9dc6-a7d6ebbd478a)

1.2
![image](https://github.com/DesobedienteTecnologico/dtails/assets/52879067/83dfa713-d297-4807-9654-1802c16d92b3)


I made it in that way because .iso files is mainly used for CDs/DVDs and it also have different partition tables and so if we compare from the .img.

https://github.com/DesobedienteTecnologico/dtails/blob/main/src/commands.py#L68-L84

At the end, we can create an ISO from it of course. But I don't really know if will be a good deal to do so.


Feedback will be appreciated. Thanks :)

**Comment by btclinux** [comment]
OK, tgen how to save a modified img?

**Comment by DesobedienteTecnologico** [comment]
1. Run those two commands:
https://github.com/DesobedienteTecnologico/dtails/blob/main/src/commands.py#L80-L81

2. Modify:
**isolinux** for **syslinux**.


Also be aware that Persistent setting will not work in that .iso


I will probably add a checkbox to create the .iso for testing purposes in VM and so.
