### ISSUE TITLE
Export modified .IMG file

### ISSUE THREAD

**Issue by hiagopdutra** [DesobedienteTecnologico/dtails#36]
Does it possible to get the modified dtails .img instead of installing it on the flash driver?

**Comment by DesobedienteTecnologico** [comment]
Actually is possible to create a .iso file from the .img.

If you do everything with a [.iso](https://tails.net/install/index.en.html), a dtails.iso will be created automatically instead of burning on the Flash driver :
![image](https://github.com/DesobedienteTecnologico/dtails/assets/52879067/698b7714-3b24-4206-bd06-afb6432cd32c)


But if you used a .img, still posible to create a .iso from it. Just use the command that is below, which [cames from here](https://github.com/DesobedienteTecnologico/dtails/blob/101ca3f86cde3c8f23e88881a488d8339c4bd694/src/commands.py#L78) with a little change (isolinux to syslinux):

`sudo genisoimage -r -J -b syslinux/isolinux.bin -c syslinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -o dtails.iso future_iso/`


📌 Use DTails as usual. When it ask you to flash it, close the window and run that command. Then a file called dtails.iso is going to be create. (Run it in the DTails root directory).


Regards

**Comment by hiagopdutra** [comment]
Thank you for the answer! 
I'd generated a .iso before, but it doesn't have persistence storage. I want to create a .img to have [encrypted persistence storage on the VM](https://www.nicksherlock.com/2020/12/running-tails-as-a-vm-with-persistence-on-proxmox/) and be able to reuse the file to create new flash drivers. 
Is it possible?

Best regards!

**Comment by DesobedienteTecnologico** [comment]
>I'd generated a .iso before, but it doesn't have persistence storage.

Hi,

As commented here, yes. [.isos do not have option for persistence](https://github.com/DesobedienteTecnologico/dtails?tab=readme-ov-file#3--iso-vs-img) because they are created for CDs/DVDs.

>I want to create a .img to have [encrypted persistence storage on the VM](https://www.nicksherlock.com/2020/12/running-tails-as-a-vm-with-persistence-on-proxmox/) and be able to reuse the file to create new flash drivers.

I highly recommend you to use a normal Flash drive and boot it from VirtualBox using this tool:

[Plop Boot Manager](https://www.plop.at/en/bootmanager/download.html)
![image](https://github.com/DesobedienteTecnologico/dtails/assets/52879067/53f9d37e-db00-4da7-820a-cc13cf2b8fd0)

1. Download and unzip the .zip file
2. There you will see a file called plpbt.iso
3. Go to VirtualBox and select that .iso to boot from it
4. Connect the USB
5. Boot the .iso from Virtualbox
6. Select the flash drive
7. Enjoy!

I haven't probably understand you well in this part:
>and be able to reuse the file to create new flash drivers

If you want to do so, -Actually- you have to use DTails and flash from there directly.

I said actually, because I'm working on a changes that allow us to create a .img file ready to ship and flash with other software if you wish what ever time you want without the need to use DTails again.

Regards, and thanks for using DTails.

**Comment by DesobedienteTecnologico** [comment]
closing due inactivity
